// MODIFICA ESTA URL POR LA DEL SERVICIO WEB DESPUES DE HABERLO DESPLEGADO
const AS_URL_BASE = "https://script.google.com/macros/s/AKfycbzruk3SrRz0Nq5v9MvcL6NLgGCO1RVT_kcKZ1gdIkYha2ZhF-7iWh229F8WsfY7kr1_qw/exec";
